#!/usr/bin/env python
"""
Build a synthetic tilt-series data set, in RELION-5 or Warp-2 form, from a known volume.

    python make_synthetic_tomo.py --flavour relion --out synth_relion
    python make_synthetic_tomo.py --flavour warp   --out synth_warp

Why this exists
---------------
Testing a metadata converter against data generated by that same converter proves
nothing: a wrong convention cancels itself. So nothing here imports
``xmipp_metadata.metadata.relion_tomo``. The geometry is built from RELION's own
semantics (``Tomogram::setProjectionMatrix``, ``ParticleSet::getMatrix4x4``,
``ParticleSet::getPosition``) transcribed independently through ``scipy``'s rotations,
and the images are rendered in **real space** -- rotate the volume, integrate along the
beam -- which is a different numerical route from the Fourier-slice insertion that
reconstructs them. If the convention were wrong, the two would disagree.

The output is meant to be what RELION or Warp would have written, not what is
convenient to read. In particular the Warp flavour writes ``rlnTomoProj*`` with a
literal zero translation column, because that is what WarpTools does
(``$"[{M.M11},{M.M12},{M.M13},0]"``), and any reader that needs the translation to
place a particle will fail on it exactly as it fails on real Warp output.

What is written
---------------
    <out>/                          the project root; star paths are relative to it
      ground_truth/phantom.mrc      the volume every reconstruction must reproduce
      ground_truth/poses.npz        the per-tilt-image pose actually used to render
    <out>/README.md                 the commands to run, with the expected outcome

``poses.npz`` is the point of the exercise: reconstructing with *those* poses proves
the renderer is self-consistent, and reconstructing with the poses a converter derives
from the star files proves the converter agrees with it. The second is the real test.
"""

import argparse
import os

import numpy as np
import pandas as pd
import starfile
from scipy.ndimage import affine_transform
from scipy.spatial.transform import Rotation as Rot

try:
    import mrcfile
except ImportError:  # pragma: no cover
    raise SystemExit("mrcfile is required: pip install mrcfile")


# --------------------------------------------------------------------------- #
#  Conventions, derived independently of the code under test
# --------------------------------------------------------------------------- #

def relion_matrix(rot, tilt, psi):
    """RELION's ``Euler_angles2matrix``.

    Reached through scipy rather than by re-typing RELION's trigonometry, so that a
    typo in one is not reproduced in the other: scipy's intrinsic ZYZ matrix is exactly
    RELION's transpose (verified to 4e-16 over random draws).
    """
    return Rot.from_euler("ZYZ", [rot, tilt, psi], degrees=True).as_matrix().T


def _translation(t):
    m = np.eye(4)
    m[:3, 3] = t
    return m


def _axis_rotation(axis, angle_deg):
    """gravis ``t3Matrix::rotation(axis, angle)`` -- Rodrigues, angle in DEGREES."""
    m = np.eye(4)
    m[:3, :3] = Rot.from_rotvec(np.deg2rad(angle_deg) * np.asarray(axis, float)).as_matrix()
    return m


def projection_matrices(x_tilt, y_tilt, z_rot, x_shift_a, y_shift_a, apix,
                        tomo_size, image_size):
    """``Tomogram::setProjectionMatrix``: ``s1 * s2 * r2 * r1 * r0 * s0``.

    Maps a position in unbinned tomogram pixels to a position in the tilt image. Note
    the integer halving of the centres -- RELION uses ``((int) w) / 2``, not ``w / 2``.
    """
    w0, h0, d0 = tomo_size
    out = np.zeros((len(x_tilt), 4, 4))
    for f in range(len(x_tilt)):
        s0 = _translation(-np.array([int(w0) // 2, int(h0) // 2, int(d0) // 2], float))
        r0 = _axis_rotation((1, 0, 0), x_tilt[f])
        r1 = _axis_rotation((0, 1, 0), y_tilt[f])
        r2 = _axis_rotation((0, 0, 1), z_rot[f])
        s1 = _translation([x_shift_a[f] / apix, y_shift_a[f] / apix, 0.0])
        s2 = _translation([int(image_size[0]) // 2, int(image_size[1]) // 2, 0.0])
        out[f] = s1 @ s2 @ r2 @ r1 @ r0 @ s0
    return out


# --------------------------------------------------------------------------- #
#  The phantom
# --------------------------------------------------------------------------- #

# Deliberately chiral: a right-handed arrangement of blobs of unequal size, so a
# mirrored reconstruction is obviously wrong rather than merely rotated. Positions and
# widths are FRACTIONS of the box edge, not Angstrom, so the phantom scales with the box
# and always fits: a phantom that pokes out of its box is clipped differently at every
# orientation, which alone drags the achievable FSC from 0.99 down to 0.58.
_BLOBS = [
    ((0.000, 0.000, 0.000), 0.085, 1.00),
    ((0.150, 0.000, -0.045), 0.055, 0.85),
    ((0.045, 0.140, 0.026), 0.046, 0.75),
    ((-0.130, 0.058, 0.085), 0.039, 0.70),
    ((-0.078, -0.120, -0.065), 0.049, 0.65),
    ((0.098, -0.098, 0.110), 0.033, 0.60),
    ((-0.020, 0.033, -0.155), 0.036, 0.55),
]


def phantom(box, apix):
    """Sample the phantom analytically, so any box and pixel size is exact."""
    extent = box * apix
    g = (np.arange(box) - box // 2) * apix
    z, y, x = np.meshgrid(g, g, g, indexing="ij")
    vol = np.zeros((box, box, box), np.float32)
    for (cx, cy, cz), sigma, amp in _BLOBS:
        s = sigma * extent
        vol += amp * np.exp(-(((x - cx * extent) ** 2 + (y - cy * extent) ** 2
                               + (z - cz * extent) ** 2) / (2.0 * s ** 2)))
    return vol


def integrate_along_beam(volume, R):
    """Rotate the volume by ``R`` and integrate along z -- a real-space projection.

    ``R`` maps volume coordinates to image coordinates, RELION's convention, so the
    image is ``I(x, y) = INT V(R^-1 (x, y, w)) dw``. Done with a real-space resampling
    rather than a central Fourier slice on purpose: the reconstruction under test is
    Fourier-slice based, and using the same machinery to make the data would hide any
    error the two share.
    """
    n = volume.shape[0]
    # Rotate about box//2, the voxel fftshift calls the origin. Using the geometric
    # centre (n-1)/2 instead puts every image half a pixel out by an orientation-dependent
    # amount, costing ~0.07 of median FSC -- small enough to be mistaken for a convention
    # error, which is exactly why it is spelled out here.
    c = float(n // 2)
    swap = np.array([[0, 0, 1], [0, 1, 0], [1, 0, 0]], float)   # (x,y,z) <-> array (z,y,x)
    M = swap @ R.T @ swap
    offset = np.full(3, c) - M @ np.full(3, c)
    rotated = affine_transform(volume, M, offset=offset, order=3,
                               mode="constant", cval=0.0)
    return rotated.sum(axis=0).astype(np.float32)               # [row, col] = [y, x]


def fourier_crop(image, box):
    """Downsample by cropping the centred transform, as RELION's extraction does."""
    n = image.shape[0]
    if n == box:
        return image.astype(np.float32)
    ft = np.fft.fftshift(np.fft.fft2(np.fft.ifftshift(image)))
    lo = n // 2 - box // 2
    ft = ft[lo:lo + box, lo:lo + box]
    out = np.fft.fftshift(np.fft.ifft2(np.fft.ifftshift(ft)))
    return np.real(out).astype(np.float32) * (box / n) ** 2


def shift_image(image, dx, dy):
    """Translate image content by (dx, dy) pixels, sub-pixel exact."""
    n = image.shape[0]
    f = np.fft.fftfreq(n)
    fy, fx = np.meshgrid(f, f, indexing="ij")
    ft = np.fft.fft2(image) * np.exp(-2j * np.pi * (dx * fx + dy * fy))
    return np.real(np.fft.ifft2(ft)).astype(np.float32)


# --------------------------------------------------------------------------- #
#  Contrast transfer and radiation damage
# --------------------------------------------------------------------------- #

def ctf(box, apix, du, dv, angle_deg, kv, cs_mm, q0, scale=1.0, phase_shift=0.0):
    """Standard CTF on a centred grid, written out rather than imported."""
    wl = 12.2639 / np.sqrt(kv * 1e3 + 0.97845 * kv ** 2)         # Angstrom
    cs = cs_mm * 1e7                                            # mm -> Angstrom
    g = np.fft.fftshift(np.fft.fftfreq(box)) / apix
    ky, kx = np.meshgrid(g, g, indexing="ij")
    k2 = kx ** 2 + ky ** 2
    a = np.arctan2(ky, kx)

    dz = 0.5 * (du + dv) + 0.5 * (du - dv) * np.cos(2.0 * (a - np.deg2rad(angle_deg)))
    chi = (np.pi * wl * k2 * dz - 0.5 * np.pi * cs * wl ** 3 * k2 ** 2
           + np.deg2rad(phase_shift))
    return (scale * (np.sqrt(1.0 - q0 ** 2) * np.sin(chi) + q0 * np.cos(chi))).astype(np.float32)


def dose_weight(box, apix, dose):
    """Grant & Grigorieff critical-dose weighting -- a definition, not a convention."""
    g = np.fft.fftshift(np.fft.fftfreq(box)) / apix
    ky, kx = np.meshgrid(g, g, indexing="ij")
    k = np.maximum(np.sqrt(kx ** 2 + ky ** 2), 1e-6)
    n_c = 0.24499 * k ** -1.6649 + 2.8141
    return np.exp(-dose / (2.0 * n_c)).astype(np.float32)


def apply_in_fourier(image, filt):
    ft = np.fft.fftshift(np.fft.fft2(np.fft.ifftshift(image)))
    return np.real(np.fft.fftshift(np.fft.ifft2(np.fft.ifftshift(ft * filt)))).astype(np.float32)


# --------------------------------------------------------------------------- #
#  The data set
# --------------------------------------------------------------------------- #

def build(args):
    rng = np.random.default_rng(args.seed)
    apix_ts = args.apix
    binning = args.binning
    apix_img = apix_ts * binning
    box = args.box                       # output box, at apix_img
    box_unb = box * binning              # rendered box, at apix_ts
    F = args.tilts
    W, H = args.tilt_image, args.tilt_image
    tomo_size = (W, H, args.tomo_z)
    tomo_centre = np.array([int(W) // 2, int(H) // 2, int(args.tomo_z) // 2], float)

    # ---- tilt-series geometry ------------------------------------------------ #
    y_tilt = np.linspace(-args.max_tilt, args.max_tilt, F)
    x_tilt = rng.uniform(-1.5, 1.5, F)
    z_rot = rng.uniform(-180, 180, F) if args.random_zrot else np.full(F, 85.0) + rng.uniform(-2, 2, F)
    x_shift = rng.uniform(-40, 40, F)
    y_shift = rng.uniform(-40, 40, F)
    defocus_u = rng.uniform(20000, 40000, F)
    defocus_v = defocus_u + rng.uniform(-800, 800, F)
    defocus_ang = rng.uniform(0, 180, F)
    scalefactor = np.cos(np.deg2rad(y_tilt))
    pre_exposure = np.arange(F) * args.dose_per_tilt
    hand = float(args.hand)

    P = projection_matrices(x_tilt, y_tilt, z_rot, x_shift, y_shift, apix_ts,
                            tomo_size, (W, H))
    if args.flavour == "warp":
        # WarpTools writes the rotation and a hard zero translation column. Keeping the
        # real translation here would make the file easier to read and less honest.
        P_written = P.copy()
        P_written[:, :3, 3] = 0.0
    else:
        P_written = P

    # ---- particles ----------------------------------------------------------- #
    M = args.particles
    half = 0.5 * box_unb
    true_pos = np.stack([
        rng.uniform(half, W - half, M),
        rng.uniform(half, H - half, M),
        rng.uniform(0.3 * args.tomo_z, 0.7 * args.tomo_z, M)], axis=1)

    A_part = np.stack([relion_matrix(*a) for a in np.stack([
        rng.uniform(-180, 180, M), rng.uniform(0, 180, M), rng.uniform(-180, 180, M)],
        axis=1)])
    ang_part = np.array([_matrix_to_relion_angles(A) for A in A_part])

    if args.subtomogram_angles:
        A_sub_ang = np.stack([rng.uniform(-180, 180, M), rng.uniform(0, 180, M),
                              rng.uniform(-180, 180, M)], axis=1)
        A_sub = np.stack([relion_matrix(*a) for a in A_sub_ang])
    else:
        A_sub_ang = None
        A_sub = np.tile(np.eye(3), (M, 1, 1))

    # The particle was extracted at `coord`, and refined to `true_pos` afterwards. RELION
    # stores the extraction coordinate and expresses the correction as an origin, with
    # true = coord - A_sub * offset / apix  (ParticleSet::getPosition).
    err = rng.uniform(-args.origin_error, args.origin_error, (M, 3)) / apix_ts
    coord = true_pos + err
    offset_angst = np.einsum('nji,nj->ni', A_sub, coord - true_pos) * apix_ts

    visible = np.ones((M, F), dtype=int)

    # ---- render -------------------------------------------------------------- #
    vol_unb = phantom(box_unb, apix_ts)
    truth = phantom(box, apix_img)

    tilts = (np.zeros((F, H, W), np.float32) if args.write_tilt_series else None)
    stacks, true_poses = {}, []
    print(f"rendering {M} particles x {F} tilts at box {box_unb} -> {box} ...")
    for p in range(M):
        frames = np.zeros((F, box, box), np.float32)
        for f in range(F):
            R_tot = P[f][:3, :3] @ A_sub[p] @ A_part[p]

            # where the particle really is in this tilt, versus where it was cropped
            centre_true = (P[f] @ np.append(true_pos[p], 1.0))[:2]
            centre_crop = (P[f] @ np.append(coord[p], 1.0))[:2]
            d = (centre_true - centre_crop) / binning        # in output pixels

            raw = integrate_along_beam(vol_unb, R_tot)
            img = shift_image(fourier_crop(raw, box), d[0], d[1])

            depth = (P[f] @ np.append(true_pos[p], 1.0))[2]
            dz = hand * apix_ts * depth
            c = ctf(box, apix_img, defocus_u[f] + dz, defocus_v[f] + dz,
                    defocus_ang[f], args.kv, args.cs, args.q0, scale=scalefactor[f])
            w = dose_weight(box, apix_img, pre_exposure[f]) if args.dose_weighting else 1.0

            # The stored image is what an extraction writes: the observation, damped by
            # radiation damage, then pre-multiplied by the same CTF*W matched filter.
            # Pre-multiplied is what RELION's and Warp's extractions actually write, but
            # a plain observation lets RELION's own single-particle reconstructor be
            # pointed at the converted metadata without hand-editing an optics flag.
            frames[f] = apply_in_fourier(img, (c * w) ** 2 if args.premultiply else c * w)

            if tilts is not None:
                # The tilt image holds the *observation*, filtered by CTF*W once and not
                # pre-multiplied -- that is what a microscope produces and what RELION or
                # Warp expect to extract from. Rendered unbinned, at the tilt-series
                # sampling, and dropped in at the particle's true projected position.
                cu = ctf(box_unb, apix_ts, defocus_u[f] + dz, defocus_v[f] + dz,
                         defocus_ang[f], args.kv, args.cs, args.q0, scale=scalefactor[f])
                wu = dose_weight(box_unb, apix_ts, pre_exposure[f]) if args.dose_weighting else 1.0
                base = np.rint(centre_true).astype(int)
                sub = centre_true - base
                patch = apply_in_fourier(shift_image(raw, sub[0], sub[1]), cu * wu)
                x0, y0 = base[0] - box_unb // 2, base[1] - box_unb // 2
                xs, ys = slice(max(x0, 0), min(x0 + box_unb, W)), slice(max(y0, 0), min(y0 + box_unb, H))
                px, py = slice(xs.start - x0, xs.stop - x0), slice(ys.start - y0, ys.stop - y0)
                if xs.stop > xs.start and ys.stop > ys.start:
                    tilts[f, ys, xs] += patch[py, px]
            if args.snr > 0:
                frames[f] += rng.normal(0.0, frames[f].std() / np.sqrt(args.snr),
                                        frames[f].shape).astype(np.float32)

            true_poses.append((p, f) + _matrix_to_relion_angles(R_tot)
                              + (-d[0], -d[1]))
        stacks[p] = frames
        if (p + 1) % 10 == 0:
            print(f"  {p + 1}/{M}")

    return dict(locals())


def _matrix_to_relion_angles(A):
    """Inverse of ``relion_matrix``, through scipy for the same reason."""
    rot, tilt, psi = Rot.from_matrix(A.T).as_euler("ZYZ", degrees=True)
    return float(rot), float(tilt), float(psi)


def _vec(v):
    return "[" + ",".join(f"{x:.6f}" for x in np.asarray(v).ravel()) + "]"


def _write_stacks(root, rel_dir, stacks, visible):
    """One 2D stack per particle, holding only the visible tilts, in frame order."""
    os.makedirs(os.path.join(root, rel_dir), exist_ok=True)
    names = []
    for p, frames in stacks.items():
        keep = frames[visible[p].astype(bool)]
        rel = f"{rel_dir}/{p + 1:06d}_stack2d.mrcs"
        with mrcfile.new(os.path.join(root, rel), overwrite=True) as m:
            m.set_data(keep.astype(np.float32))
        names.append(rel)
    return names


def write_relion(d, out):
    """A RELION-5 project: tomograms set, tilt-series set, extracted particles."""
    os.makedirs(out, exist_ok=True)
    F, M = d["F"], d["M"]
    name = "TS_01"

    tilt_rel = None
    if d["tilts"] is not None:
        os.makedirs(os.path.join(out, "tilt_series"), exist_ok=True)
        tilt_rel = f"tilt_series/{name}.mrcs"
        with mrcfile.new(os.path.join(out, tilt_rel), overwrite=True) as m:
            m.set_data(d["tilts"].astype(np.float32))
            m.voxel_size = d["apix_ts"]

    ts = pd.DataFrame({
        "rlnMicrographName": [f"{f + 1:06d}@{tilt_rel}" if tilt_rel
                              else f"frames/{name}_{f:03d}.mrc" for f in range(F)],
        "rlnTomoXTilt": d["x_tilt"],
        "rlnTomoYTilt": d["y_tilt"],
        "rlnTomoZRot": d["z_rot"],
        "rlnTomoXShiftAngst": d["x_shift"],
        "rlnTomoYShiftAngst": d["y_shift"],
        "rlnDefocusU": d["defocus_u"],
        "rlnDefocusV": d["defocus_v"],
        "rlnDefocusAngle": d["defocus_ang"],
        "rlnCtfScalefactor": d["scalefactor"],
        "rlnMicrographPreExposure": d["pre_exposure"],
        "rlnCtfFigureOfMerit": np.full(F, 0.1),
    })
    os.makedirs(os.path.join(out, "Tomograms/job001/tilt_series"), exist_ok=True)
    ts_rel = "Tomograms/job001/tilt_series/TS_01.star"
    starfile.write({name: ts}, os.path.join(out, ts_rel), overwrite=True)

    glob = pd.DataFrame([{
        "rlnTomoName": name,
        "rlnVoltage": d["args"].kv,
        "rlnSphericalAberration": d["args"].cs,
        "rlnAmplitudeContrast": d["args"].q0,
        "rlnTomoTiltSeriesPixelSize": d["apix_ts"],
        "rlnTomoHand": d["hand"],
        "rlnTomoSizeX": d["W"], "rlnTomoSizeY": d["H"], "rlnTomoSizeZ": d["args"].tomo_z,
        "rlnTomoTiltSeriesStarFile": ts_rel,
        "rlnTomoTiltSeriesName": tilt_rel if tilt_rel else "tilt_series/TS_01.mrcs",
        "rlnOpticsGroupName": "opticsGroup1",
        "rlnTomoImportFractionalDose": d["args"].dose_per_tilt,
    }])
    tomo_rel = "Tomograms/job001/tomograms.star"
    starfile.write({"global": glob}, os.path.join(out, tomo_rel), overwrite=True)

    names = _write_stacks(out, "Extract/job002/Subtomograms/TS_01",
                          d["stacks"], d["visible"])
    centred = (d["coord"] - d["tomo_centre"]) * d["apix_ts"]

    parts = pd.DataFrame({
        "rlnTomoName": [name] * M,
        "rlnTomoParticleId": np.arange(1, M + 1),
        "rlnTomoParticleName": [f"{name}/{i + 1}" for i in range(M)],
        "rlnCenteredCoordinateXAngst": centred[:, 0],
        "rlnCenteredCoordinateYAngst": centred[:, 1],
        "rlnCenteredCoordinateZAngst": centred[:, 2],
        "rlnAngleRot": d["ang_part"][:, 0],
        "rlnAngleTilt": d["ang_part"][:, 1],
        "rlnAnglePsi": d["ang_part"][:, 2],
        "rlnOriginXAngst": d["offset_angst"][:, 0],
        "rlnOriginYAngst": d["offset_angst"][:, 1],
        "rlnOriginZAngst": d["offset_angst"][:, 2],
        "rlnTomoVisibleFrames": ["[" + ",".join(map(str, v)) + "]" for v in d["visible"]],
        "rlnImageName": names,
        "rlnOpticsGroup": np.ones(M, dtype=int),
        "rlnRandomSubset": np.arange(1, M + 1) % 2 + 1,
    })
    if d["A_sub_ang"] is not None:
        parts["rlnTomoSubtomogramRot"] = d["A_sub_ang"][:, 0]
        parts["rlnTomoSubtomogramTilt"] = d["A_sub_ang"][:, 1]
        parts["rlnTomoSubtomogramPsi"] = d["A_sub_ang"][:, 2]

    optics = pd.DataFrame([{
        "rlnOpticsGroup": 1,
        "rlnOpticsGroupName": "opticsGroup1",
        "rlnSphericalAberration": d["args"].cs,
        "rlnVoltage": d["args"].kv,
        "rlnAmplitudeContrast": d["args"].q0,
        "rlnTomoTiltSeriesPixelSize": d["apix_ts"],
        "rlnImagePixelSize": d["apix_img"],
        "rlnImageSize": d["box"],
        "rlnImageDimensionality": 2,
        "rlnTomoSubtomogramBinning": float(d["binning"]),
        "rlnCtfDataAreCtfPremultiplied": int(d["args"].premultiply),
    }])
    parts_rel = "Extract/job002/particles.star"
    starfile.write({"optics": optics, "particles": parts},
                   os.path.join(out, parts_rel), overwrite=True)

    opt = ["# version 50001", "", "data_optimisation_set", "",
           f"_rlnTomoParticlesFile        {parts_rel}",
           f"_rlnTomoTomogramsFile        {tomo_rel}", ""]
    with open(os.path.join(out, "Extract/job002/optimisation_set.star"), "w") as fh:
        fh.write("\n".join(opt))
    return "Extract/job002/optimisation_set.star"


def _warp_tilt_stack(d, out):
    if d["tilts"] is None:
        return "tiltstack/TS_01/TS_01.mrc"
    os.makedirs(os.path.join(out, "tiltstack/TS_01"), exist_ok=True)
    rel = "tiltstack/TS_01/TS_01.mrc"
    with mrcfile.new(os.path.join(out, rel), overwrite=True) as m:
        m.set_data(d["tilts"].astype(np.float32))
        m.voxel_size = d["apix_ts"]
    return rel


def write_warp(d, out):
    """A WarpTools ``ts_export_particles --2d`` style export."""
    os.makedirs(out, exist_ok=True)
    F, M = d["F"], d["M"]
    name = "TS_01.tomostar"
    P = d["P_written"]

    ts = pd.DataFrame({
        "rlnTomoProjX": [_vec(P[f, 0]) for f in range(F)],
        "rlnTomoProjY": [_vec(P[f, 1]) for f in range(F)],
        "rlnTomoProjZ": [_vec(P[f, 2]) for f in range(F)],
        "rlnTomoProjW": [_vec(P[f, 3]) for f in range(F)],
        "rlnDefocusU": d["defocus_u"],
        "rlnDefocusV": d["defocus_v"],
        "rlnDefocusAngle": d["defocus_ang"],
        "rlnPhaseShift": np.zeros(F),
        "rlnCtfScalefactor": d["scalefactor"],
        "rlnMicrographPreExposure": d["pre_exposure"],
    })
    glob = pd.DataFrame([{
        "rlnTomoName": name,
        "rlnTomoTiltSeriesName": _warp_tilt_stack(d, out),
        "rlnTomoFrameCount": F,
        "rlnTomoSizeX": d["W"], "rlnTomoSizeY": d["H"], "rlnTomoSizeZ": d["args"].tomo_z,
        "rlnTomoHand": d["hand"],
        "rlnOpticsGroupName": "TS_01",
        "rlnTomoTiltSeriesPixelSize": d["apix_ts"],
        "rlnVoltage": d["args"].kv,
        "rlnSphericalAberration": d["args"].cs,
        "rlnAmplitudeContrast": d["args"].q0,
        "rlnTomoImportFractionalDose": d["args"].dose_per_tilt,
    }])
    tomo_rel = "matching_tomograms.star"
    starfile.write({"global": glob, name: ts}, os.path.join(out, tomo_rel), overwrite=True)

    names = _write_stacks(out, "particleseries/TS_01", d["stacks"], d["visible"])
    centred = (d["coord"] - d["tomo_centre"]) * d["apix_ts"]

    parts = pd.DataFrame({
        "rlnTomoName": [name] * M,
        "rlnTomoParticleId": np.arange(1, M + 1),
        "rlnTomoParticleName": [f"TS_01/{i + 1}" for i in range(M)],
        "rlnCenteredCoordinateXAngst": centred[:, 0],
        "rlnCenteredCoordinateYAngst": centred[:, 1],
        "rlnCenteredCoordinateZAngst": centred[:, 2],
        "rlnAngleRot": d["ang_part"][:, 0],
        "rlnAngleTilt": d["ang_part"][:, 1],
        "rlnAnglePsi": d["ang_part"][:, 2],
        "rlnOriginXAngst": d["offset_angst"][:, 0],
        "rlnOriginYAngst": d["offset_angst"][:, 1],
        "rlnOriginZAngst": d["offset_angst"][:, 2],
        "rlnTomoVisibleFrames": ["[" + ",".join(map(str, v)) + "]" for v in d["visible"]],
        "rlnImageName": names,
        "rlnOpticsGroup": ["TS_01"] * M,          # Warp writes a string here
        "rlnRandomSubset": np.arange(1, M + 1) % 2 + 1,
    })
    optics = pd.DataFrame([{
        "rlnOpticsGroup": "TS_01",
        "rlnSphericalAberration": d["args"].cs,
        "rlnVoltage": d["args"].kv,
        "rlnAmplitudeContrast": d["args"].q0,
        "rlnImagePixelSize": d["apix_img"],
        "rlnImageSize": d["box"],
        "rlnImageDimensionality": 2,
        "rlnCtfDataAreCtfPremultiplied": int(d["args"].premultiply),
    }])
    parts_rel = "matching.star"
    starfile.write({"optics": optics, "particles": parts},
                   os.path.join(out, parts_rel), overwrite=True)
    return parts_rel


def write_ground_truth(d, out, entry):
    gt = os.path.join(out, "ground_truth")
    os.makedirs(gt, exist_ok=True)
    with mrcfile.new(os.path.join(gt, "phantom.mrc"), overwrite=True) as m:
        m.set_data(d["truth"].astype(np.float32))
        m.voxel_size = d["apix_img"]

    poses = np.array(d["true_poses"], float)
    np.savez(os.path.join(gt, "poses.npz"), particle=poses[:, 0], frame=poses[:, 1],
             rot=poses[:, 2], tilt=poses[:, 3], psi=poses[:, 4],
             shift_x=poses[:, 5], shift_y=poses[:, 6], apix=d["apix_img"],
             box=d["box"])

    ctf_mode = "premultiplied" if d["args"].premultiply else "apply"
    have_tilts = d["tilts"] is not None
    readme = f"""# Synthetic {d['args'].flavour} tilt-series data set

Ground truth: `ground_truth/phantom.mrc` ({d['box']}^3 at {d['apix_img']:.3f} A/px).
Every reconstruction below must reproduce it.

Generated independently of the converter under test: the geometry comes from RELION's
own algebra transcribed through scipy, and the images are rendered in real space
(rotate the volume, integrate along the beam) rather than by Fourier slicing.

    particles      : {entry}
    tilts          : {d['F']}   particles: {d['M']}
    tilt-series px : {d['apix_ts']:.3f} A      binning: {d['binning']} -> {d['apix_img']:.3f} A/px
    tilt images    : {"tilt_series/ (rendered)" if have_tilts else "NOT rendered (pass --write-tilt-series)"}
    handedness     : {d['hand']:+.0f}
    origins        : refined up to {d['args'].origin_error:.1f} A after extraction
    stored images  : {"pre-multiplied by (CTF*W)^2" if d['args'].premultiply else "plain CTF*W observations"}
    noise          : {'SNR ' + str(d['args'].snr) if d['args'].snr > 0 else 'none'}

Run everything below from THIS directory: the star files use project-relative paths,
exactly as RELION writes them.

## 1. hax

    hax_project_manager --gpu 0 reconstruct_volume --md {entry} \\
        --sr {d['apix_img']:.4f} --ctf_type {ctf_mode} --no_denoise

    python /path/to/tools/compare_volumes.py ground_truth/phantom.mrc \\
        consensus_reconstruction.mrc --apix {d['apix_img']:.4f}

## 2. The metadata alone, no GPU

    python /path/to/tools/validate_synthetic.py .

Two stages: from the poses the images were rendered with, then from the poses the
converter derives. The second reproducing the first is the actual test. Use
`--break transpose|mirror|drop-shifts|swap-rot-psi` to confirm it can fail.

## 3. RELION reconstructing the same data itself
{"" if have_tilts else "   (regenerate with --write-tilt-series first -- RELION extracts from the tilt images)"}
    relion_tomo_reconstruct_particle --i {entry} --o Reconstruct/ \\
        --b {d['box']} --crop {d['box']} --bin {d['binning']} --sym C1 --j 8

    python /path/to/tools/compare_volumes.py ground_truth/phantom.mrc \\
        Reconstruct/merged.mrc --apix {d['apix_img']:.4f}

If RELION reproduces the phantom from these files, they really are what RELION expects,
and hax agreeing with RELION then means the conversion is right rather than merely
self-consistent. This is the only step that tests the *files* rather than the reader.

## 4. RELION's single-particle reconstructor on the converted metadata

Needs no tilt images, and is the most direct statement that the conversion is correct in
RELION's own convention -- RELION reads the per-tilt alignment this package produced:

    python -c "
    from xmipp_metadata.metadata import XmippMetaData
    md = XmippMetaData('{entry}')
    md.write('particles_tilts.star', updateImagePaths=True)"

    relion_reconstruct --i particles_tilts.star --o relion_spa.mrc --ctf{"" if d['args'].premultiply else ""}

Generate with `--no-premultiply` for this one: relion_reconstruct takes the
pre-multiplied flag from the optics block, which the Xmipp-to-RELION writer does not
carry through, so a pre-multiplied stack would be CTF-weighted twice.

## 5. Warp

Warp's role in this pipeline is export, not averaging -- the meaningful check for the
warp flavour is step 3, RELION reconstructing from a Warp-shaped export, which is the
real pipeline. Note this data set carries Warp's literal zero translation column in
`rlnTomoProj*`, so anything needing that translation to place a particle will fail on
it, exactly as it does on real WarpTools output.

## Reading the result

FSC ~ 1.0 to Nyquist means the conventions agree. Disagreement from the lowest shells is
a pose or shift convention error; a high correlation only after mirroring means the
handedness is inverted. Do not judge by correlation alone -- in the sabotage tests CC
stayed above 0.92 for every corruption that the FSC caught.
"""
    with open(os.path.join(out, "README.md"), "w") as fh:
        fh.write(readme)


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--flavour", choices=("relion", "warp"), required=True)
    p.add_argument("--out", required=True)
    p.add_argument("--particles", type=int, default=40)
    p.add_argument("--tilts", type=int, default=25)
    p.add_argument("--box", type=int, default=48, help="output box, in binned pixels")
    p.add_argument("--binning", type=int, default=2)
    p.add_argument("--apix", type=float, default=2.0, help="tilt-series pixel size")
    p.add_argument("--tilt-image", type=int, default=1024)
    p.add_argument("--tomo-z", type=int, default=400)
    p.add_argument("--max-tilt", type=float, default=54.0)
    p.add_argument("--dose-per-tilt", type=float, default=3.0)
    p.add_argument("--origin-error", type=float, default=12.0,
                   help="size of the post-extraction refinement, in Angstrom")
    p.add_argument("--hand", type=float, default=-1.0, choices=(-1.0, 1.0))
    p.add_argument("--kv", type=float, default=300.0)
    p.add_argument("--cs", type=float, default=2.7)
    p.add_argument("--q0", type=float, default=0.07)
    p.add_argument("--snr", type=float, default=0.0)
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--subtomogram-angles", action="store_true",
                   help="also write rlnTomoSubtomogram*, so A_sub is not the identity")
    p.add_argument("--no-dose-weighting", dest="dose_weighting", action="store_false")
    p.add_argument("--no-premultiply", dest="premultiply", action="store_false",
                   help="store plain CTF*W observations instead of pre-multiplied ones")
    p.add_argument("--random-zrot", action="store_true")
    p.add_argument("--write-tilt-series", action="store_true",
                   help="also render the full tilt images, so RELION or Warp can run "
                        "their own extraction and reconstruction on this data set")
    args = p.parse_args()

    d = build(args)
    d["args"] = args
    entry = write_relion(d, args.out) if args.flavour == "relion" else write_warp(d, args.out)
    write_ground_truth(d, args.out, entry)
    print(f"\nwrote {args.flavour} data set to {args.out}/")
    print(f"  entry point : {entry}")
    print(f"  ground truth: ground_truth/phantom.mrc")
    print(f"  see {args.out}/README.md for the commands")


if __name__ == "__main__":
    main()
